mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('louslist.urls')),
    path('admin/', admin.site.urls),
    path('login/', include('louslist.urls')),
    path('accounts/', include('allauth.urls')),
    path('profiles/', include('louslist.urls')),
]

polls/urls.py
from django.urls import path, include
from django.contrib import admin

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    #path('login', include('main.urls')),
]

polls/templates/polls/index.html
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<script src="https://apis.google.com/js/platform.js" async defer></script>

<meta name="google-signin-client_id" content="325930513099-ibniatcvkcusnjiqhuised9uviau90fh.apps.googleusercontent.com">

<script>
gapi.load('auth2', function() {
    gapi.auth2.init();
})
</script>

<nav class="navbar navbar-expand-lg bg-secondary text-white d-flex justify-content-center">
    <h1 class="p-3">Index</h1>
    <div class="flex p-2">
        <a class="text-white" href="">Votes</a>
        <a class="text-white" href="">Choice</a>
        <a class="text-white" href="">Deepthoughts</a>
    </div>
</nav>



<script>
    function onSignIn(googleUser) {
        var profile = googleUser.getBasicProfile();
        console.log('ID: ' + profile.getId()); // Do not send to your backend! Use an ID token instead.
        console.log('Name: ' + profile.getName());
        console.log('Image URL: ' + profile.getImageUrl());
        console.log('Email: ' + profile.getEmail()); // This is null if the 'email' scope is not present.
        window.location.replace("https://a20-uva.herokuapp.com/polls/1/");
        }
  function signOut() {
    var auth2 = gapi.auth2.getAuthInstance();
    auth2.signOut().then(function () {
      console.log('User signed out.');
    });
  }
</script>

{% if user.is_authenticated %}
    <p>Welcome, {{ user.username }} !</p>
    <a href="#" onclick="signOut();">Sign out</a>

{% else %}
    <h1></h1>
    <div class="g-signin2" data-onsuccess="onSignIn"></div>
{% endif %}

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<footer class="page-footer bg-primary font-small text-white">
    <div class="footer-copyright text-center py-3">© 2022 Jay Chadha(jrc7qt)
    </div>
  </footer>